# Generated by Django 2.1.5 on 2021-08-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0004_auto_20210726_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('log_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='recommend_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
