# Generated by Django 2.1.5 on 2021-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210801_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='log_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
